server:
  port: 8888
spring:
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      username: house
      password:
      jdbc-url: jdbc:h2:mem:testdb
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
